name: Docker Build and Publish

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'  # Watches for changes in Go files
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git SHA
        id: get_sha
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cat-ling/kitsune-proxy:${{ env.GIT_SHA }}
            ghcr.io/cat-ling/kitsune-proxy:latest
          labels: |
            org.opencontainers.image.source=https://github.com/cat-ling/kitsune-proxy
            org.opencontainers.image.description="Kitsune Proxy Docker Image"
            org.opencontainers.image.licenses=MIT
